name: CI

on: 
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      
      - name: install
        run: |
          python --version
          python -m pip install setuptools
          python -m pip install -r requirements.txt
          python -m pip install attrs==19.1.0
            
      - name: build 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: | 
          
          cd $GITHUB_WORKSPACE
          git init 
          git config user.name "Github Actions"
          git config user.email "github-actions-bot@users.noreply.github.com"
          REPOSITORY_PATH="https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
          
          git checkout master 
          jupyter-book build .
          
          git add -vf _build
          git commit -m "Deploying to gh-pages from master" --quiet && \
          git push $REPOSITORY_PATH `git subtree split --prefix book/_site master`:gh-pages --force
